### ISSUE TITLE
Change color theme

### ISSUE THREAD

**Issue by kaushal3103** [kaushal3103/Cocktails#1]
You have to change the background color theme. Use your creative imagination

**Comment by pratik9333** [comment]
I can do this assign me.

**Comment by kaushal3103** [comment]
@pratik9333 You can start with your task

**Comment by pratik9333** [comment]
Can you tell how can I regenerate Package.json file as there is no file in it? @kaushal3103

**Comment by kaushal3103** [comment]
@pratik9333 Sorry previously I failed to upload the file. But now I have uploaded you can check

**Comment by pratik9333** [comment]
@kaushal3103 bro there is no public folder too?

**Comment by kaushal3103** [comment]
@pratik9333 Check it again I have uploaded ! Sorry for the problems you are facing

**Comment by pratik9333** [comment]
Your Project is showing too many errors bro!

**Comment by kaushal3103** [comment]
@pratik9333 wait I will look into it

**Comment by kaushal3103** [comment]
@pratik9333 I have fixed all the errors now you can work onto it ! I am literally sorry for the issues you faced. Now you just have to clone the git and use npm install , npm audit fix and npm audit fix--force
Thank you regards
Raj
